### ISSUE TITLE
Publish gem to https://rubygems.org

### ISSUE THREAD

**Issue by drborges** [powerhome/paperclip-eitheror#12]
We need to release a beta version and make the gem available from https://rubygems.org.

**Comment by drborges** [comment]
@mpabegg feel free to push this gem under your rubygems account: http://guides.rubygems.org/publishing

**Comment by rendhalver** [comment]
Do we have a powerhome rubygems account?
Maybe we need one if we are going to make this public gem.

**Comment by drborges** [comment]
I'm not sure @rendhalver, but that sounds like a good idea to me. @benlangfeld, @xjunior, thoughts?

**Comment by bklang** [comment]
As far as I know, rubygems accounts are always individual, there are no org accounts. Best thing to do would be to make sure that you add enough maintainers with push rights. That means adding them to the gemspec but also adding them using the `gem` CLI.
