### ISSUE TITLE
Handle cases where storages provide different accessors.

### ISSUE THREAD

**Issue by mpabegg** [powerhome/paperclip-eitheror#9]
Right now, every method not known by `eitheror` is blindly passed over to whatever storage it deems appropriate. See [`Eitheror#usable_storage`](https://github.com/powerhome/paperclip-eitheror/blob/master/lib/paperclip/storage/eitheror.rb#L56-L65).

The problem is that we might try to call methods which the "appropriate" storage does not respond to. Think using `fog` as primary and `filesystem` as a fallback, things like `public_url` will not be available on the filesystem.

**Comment by mpabegg** [comment]
I thought we could make a simple mapping mechanism, something like:

```ruby
```

**Comment by drborges** [comment]
That seems an elegant solution. I wonder if there would be cases where no feasible mapping is applicable. For example, clients calling `EitherStorage#method` but there would not be any `OrStorage#fallback_method` we could alias to. Perhaps, allowing clients to also provide a `lambda`/`block` would be more flexible?
